---
name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
version-template: "$MAJOR.$MINOR"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
sort-direction: ascending

categories:
  - title: Breaking changes
    when:
      labels:
        - breaking-change
  - title: New features
    when:
      labels:
        - new-feature
        - feature
  - title: Bug fixes
    when:
      labels:
        - bug
        - bugfix
  - title: Enhancements
    when:
      labels:
        - enhancement
        - refactor
        - performance
  - title: Maintenance
    when:
      labels:
        - maintenance
        - chore
        - ci
  - title: Documentation
    when:
      labels:
        - documentation
  - title: Dependency updates
    when:
      labels:
        - dependencies
  - type: version-resolver
    semver-increment: minor

template: |
  ## What's changed

  $CHANGES
