import type { FloatingRule } from "./model.js";

export function escapeRe2Literal(value: string): string {
  return value.replace(/[\\.^$|?*+()[\]{}]/g, "\\$&");
}

export function renderConf(
  rules: readonly FloatingRule[],
  omarchy: boolean,
): string {
  const lines = ["# Generated by float-app. Do not edit by hand."];
  if (!omarchy) {
    lines.push(
      "windowrule = float on, match:tag floating-window",
      "windowrule = center on, match:tag floating-window",
      "windowrule = size 875 600, match:tag floating-window",
    );
  }
  for (const rule of rules) {
    const field = rule.field === "initial_class" ? "initial_class" : "class";
    lines.push(
      `windowrule = tag +floating-window, match:${field} ^${escapeRe2Literal(rule.class)}$`,
    );
  }
  return `${lines.join("\n")}\n`;
}

export function renderLua(
  rules: readonly FloatingRule[],
  omarchy: boolean,
): string {
  const lines = ["-- Generated by float-app. Do not edit by hand."];
  if (!omarchy) {
    lines.push(
      'hl.window_rule({ match = { tag = "floating-window" }, float = true })',
      'hl.window_rule({ match = { tag = "floating-window" }, center = true })',
      'hl.window_rule({ match = { tag = "floating-window" }, size = { 875, 600 } })',
    );
  }
  for (const rule of rules) {
    const field = rule.field === "initial_class" ? "initial_class" : "class";
    const pattern = `^${escapeRe2Literal(rule.class)}$`;
    lines.push(
      `hl.window_rule({ match = { ${field} = ${JSON.stringify(pattern)} }, tag = "+floating-window" })`,
    );
  }
  return `${lines.join("\n")}\n`;
}

export function includeLine(configPath: string, generatedPath: string): string {
  return configPath.endsWith(".lua")
    ? `require(${JSON.stringify(generatedPath.replace(/\.lua$/, "").replaceAll("/", "."))})`
    : `source = ${generatedPath}`;
}

const includeStart = "# float-app rules: start";
const includeEnd = "# float-app rules: end";

export function upsertInclude(content: string, include: string): string {
  const block = `${includeStart}\n${include}\n${includeEnd}`;
  const start = content.indexOf(includeStart);
  const end = content.indexOf(includeEnd, start);
  if (start !== -1 && end !== -1) {
    return (
      `${content.slice(0, start)}${block}${content.slice(end + includeEnd.length)}`.trimEnd() +
      "\n"
    );
  }
  return `${content.trimEnd()}${content ? "\n\n" : ""}${block}\n`;
}
