import { describe, expect, test } from "bun:test";
import {
  escapeRe2Literal,
  includeLine,
  renderConf,
  renderLua,
  upsertInclude,
} from "../../src/hyprland/render.js";

describe("Hyprland rule rendering", () => {
  test("escapes exact class matches", () => {
    expect(escapeRe2Literal("org.example.App[1]")).toBe(
      "org\\.example\\.App\\[1\\]",
    );
  });

  test("reuses Omarchy's floating tag", () => {
    expect(renderConf([{ class: "App", field: "class" }], true)).toBe(
      "# Generated by float-app. Do not edit by hand.\n" +
        "windowrule = tag +floating-window, match:class ^App$\n",
    );
  });

  test("defines fallback behavior for plain Hyprland", () => {
    expect(
      renderLua([{ class: "App", field: "initial_class" }], false),
    ).toContain(
      'hl.window_rule({ match = { tag = "floating-window" }, float = true })',
    );
    expect(
      renderLua([{ class: "App", field: "initial_class" }], false),
    ).toContain('match = { initial_class = "^App$" }');
  });

  test("renders includes by config type", () => {
    expect(
      includeLine("looknfeel.conf", "/home/me/.config/hypr/float-app.conf"),
    ).toBe("source = /home/me/.config/hypr/float-app.conf");
    expect(includeLine("looknfeel.lua", "float-app.lua")).toBe(
      'require("float-app")',
    );
  });

  test("replaces its managed include block", () => {
    expect(
      upsertInclude(
        "before\n# float-app rules: start\nold\n# float-app rules: end\n",
        "new",
      ),
    ).toBe("before\n# float-app rules: start\nnew\n# float-app rules: end\n");
  });
});
