---
name: CI

# yamllint disable-line rule:truthy
on:
  pull_request: {}
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/lint-oxlint.yml@f72d1eb6c310502499f5551d65ceca1e478eb266 # 20261003.0
  build:
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/build-bun-cli.yml@f72d1eb6c310502499f5551d65ceca1e478eb266 # 20261003.0
    with:
      smoke-test: ./dist/float-app --version
