---
name: CI

# yamllint disable-line rule:truthy
on:
  pull_request: {}
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check and build
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Set up mise
        uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566
      - name: Check
        run: mise run check
      - name: Build
        run: mise run build
      - name: Smoke-test executable
        run: ./dist/float-app --version
