---
name: Lint general

# yamllint disable-line rule:truthy
on:
  pull_request: {}
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  lint:
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/lint-general.yml@36527a2230bed48409ccd595b17f8344efe0acdd # 20261001.1
    with:
      lint-markdown: true
      lint-yaml: true
      lint-actions: true

  jsonlint:
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/lint-jsonlint.yml@36527a2230bed48409ccd595b17f8344efe0acdd # 20261001.1

  markdown-links:
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/lint-markdown-links.yml@36527a2230bed48409ccd595b17f8344efe0acdd # 20261001.1

  shellcheck:
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/lint-shellcheck.yml@36527a2230bed48409ccd595b17f8344efe0acdd # 20261001.1
    with:
      scandir: ./.scripts
      severity: warning
