---
name: Lint general

# yamllint disable-line rule:truthy
on:
  pull_request: {}
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  lint:
    uses: >-
      timmo001/workflows/.github/workflows/lint-general.yml@7c0c9b99547a5d90bb16f35ac848695c4b6473ab
    with:
      lint-markdown: true
      lint-yaml: true
      lint-actions: true

  jsonlint:
    uses: >-
      timmo001/workflows/.github/workflows/lint-jsonlint.yml@7c0c9b99547a5d90bb16f35ac848695c4b6473ab

  markdown-links:
    uses: >-
      timmo001/workflows/.github/workflows/lint-markdown-links.yml@7c0c9b99547a5d90bb16f35ac848695c4b6473ab

  shellcheck:
    uses: >-
      timmo001/workflows/.github/workflows/lint-shellcheck.yml@7c0c9b99547a5d90bb16f35ac848695c4b6473ab
    with:
      scandir: ./.scripts
      severity: warning
