---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  draft:
    uses: >-
      timmo001/workflows/.github/workflows/release-drafter.yml@7c0c9b99547a5d90bb16f35ac848695c4b6473ab
    permissions:
      contents: write
      pull-requests: write
